import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,ChevronDown,Search,ArrowRight,MapPin,Phone,Mail,CalendarDays, Trophy, Users, Newspaper, Megaphone, X, Eye} from 'lucide-react';
import './style.css';

const news=[
 {date:'08 Okt 2026',title:'Gubernur & DPRD Bersinergi Sukseskan Pesta Olahraga Nasional',cat:'Berita',views:55},
 {date:'05 Okt 2026',title:'Kejurnas Boling Menpora Cup, Tolak Ukur Menjelang PON',cat:'Prestasi',views:195},
 {date:'03 Sep 2026',title:'Pesta Olahraga Pantai, Bergerak Untuk Prestasi & Ekonomi',cat:'Event',views:500},
 {date:'29 Agu 2026',title:'Musprov Cabang Olahraga Gelar Agenda Utama Pemilihan Ketua',cat:'Organisasi',views:1424},
 {date:'21 Agu 2026',title:'Kolaborasi KONI dan Perguruan Tinggi Perkuat Sport Science',cat:'Berita',views:1342},
 {date:'12 Agu 2026',title:'Audiensi dan Sinergi Pembinaan Atlet Berprestasi',cat:'Berita',views:1536}
];
const announcements=[
 'Pengumuman Tender Pengadaan dan Sewa Peralatan Olahraga',
 'Pengumuman Tender Pengadaan Peralatan Pertandingan',
 'Penetapan Pemenang Pengadaan Alat Kesehatan',
 'Pengumuman Pemenang Pengadaan Obat Kontingen'
];
const sports=['Atletik','Anggar','Akuatik','Bola Basket','Bola Voli','Bulutangkis','Catur','Panahan','Renang','Senam','Sepak Bola','Taekwondo'];
const leaders=['Ketua Umum','Wakil Ketua Umum I','Wakil Ketua Umum II','Sekretaris Umum','Bendahara Umum','Ketua Bidang Binpres','Ketua Bidang Humas & IT','Ketua Bidang Organisasi'];

function App(){
 const [menu,setMenu]=useState(false); const [route,setRoute]=useState(location.hash.slice(1)||'home');
 useEffect(()=>{const fn=()=>setRoute(location.hash.slice(1)||'home');addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);
 const go=p=>{location.hash=p;setMenu(false);scrollTo(0,0)};
 return <><header className="top"><div className="ticker">Pesta Olahraga Pantai 2026 <b>•</b> 1 November 2026</div><div className="nav wrap"><a className="brand" href="#home"><span>SPORT</span><strong>NUSANTARA</strong></a><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><nav className={menu?'open':''}><a onClick={()=>go('home')}>Beranda</a><div className="drop"><a>Tentang Kami <ChevronDown size={15}/></a><div><a onClick={()=>go('profil')}>Profil</a><a onClick={()=>go('organisasi')}>Organisasi</a></div></div><div className="drop"><a>Informasi <ChevronDown size={15}/></a><div><a onClick={()=>go('berita')}>Berita</a><a onClick={()=>go('pengumuman')}>Pengumuman</a><a onClick={()=>go('prestasi')}>Prestasi</a><a onClick={()=>go('event')}>Event</a></div></div><div className="drop"><a>Olahraga <ChevronDown size={15}/></a><div><a onClick={()=>go('cabor')}>Cabang Olahraga</a><a onClick={()=>go('atlet')}>Data Atlet</a></div></div><a onClick={()=>go('vms')}>VMS</a><a className="login" onClick={()=>go('login')}>Login</a></nav></div></header>
 {route==='home'?<Home go={go}/>:<Page route={route} go={go}/>}<Footer go={go}/></>
}
function Home({go}){return <main><section className="hero"><div className="heroBg"></div><div className="wrap heroText"><div className="eyebrow">PUSAT PRESTASI OLAHRAGA</div><h1>Jakarta Bergerak.<br/><span>Indonesia Menang.</span></h1><p>Membangun ekosistem olahraga prestasi melalui pembinaan atlet, kompetisi, inovasi, dan kolaborasi.</p><div className="actions"><button onClick={()=>go('prestasi')}>Lihat Prestasi <ArrowRight/></button><button className="ghost" onClick={()=>go('event')}>Kalender Event</button></div></div></section><Countdown/><section className="section wrap"><div className="sectionHead"><div><small>AGENDA HARI INI</small><h2>Event & Kalender</h2></div><button onClick={()=>go('event')} className="textBtn">Lihat semua <ArrowRight size={17}/></button></div><div className="eventCard"><div className="dateBox"><b>05</b><span>OKT<br/>2026</span></div><div><small>AGENDA OLAHRAGA</small><h3>Seleksi Atlet Nasional — Cabang Atletik</h3><p><MapPin size={16}/> Stadion Utama, Jakarta</p></div><ArrowRight className="cardArrow"/></div></section><section className="darkSection"><div className="wrap"><div className="sectionHead light"><div><small>MEREKA YANG MENGINSPIRASI</small><h2>Sang Juara.</h2></div><button onClick={()=>go('prestasi')} className="textBtn">Lihat semua <ArrowRight size={17}/></button></div><div className="champ"><div className="champImg"></div><div className="champText"><span>MEDALI EMAS</span><h3>Prestasi Atlet<br/>Untuk Negeri</h3><p>Catatan prestasi terbaik lahir dari latihan, disiplin, dan dukungan ekosistem olahraga yang kuat.</p><button onClick={()=>go('prestasi')}>Jelajahi prestasi <ArrowRight/></button></div></div></div></section><section className="section wrap"><div className="sectionHead"><div><small>TETAP TERHUBUNG</small><h2>Pengumuman</h2></div><button onClick={()=>go('pengumuman')} className="textBtn">Lihat semua <ArrowRight size={17}/></button></div><div className="announceGrid">{announcements.map((x,i)=><article className="announce" key={x}><Megaphone/><small>Pengumuman • 2026</small><h3>{x}</h3><span>{270-i*31} kali dilihat</span><a onClick={()=>go('pengumuman')}>Baca <ArrowRight size={15}/></a></article>)}</div></section><section className="section newsSec"><div className="wrap"><div className="sectionHead"><div><small>KABAR TERKINI</small><h2>Berita.</h2></div><button onClick={()=>go('berita')} className="textBtn">Semua berita <ArrowRight size={17}/></button></div><div className="newsGrid">{news.slice(0,3).map((n,i)=><NewsCard n={n} key={i}/>)}</div></div></section></main>}
function Countdown(){const [left,setLeft]=useState({d:0,h:0,m:0,s:0});useEffect(()=>{const end=new Date('2026-11-01T00:00:00');const tick=()=>{let x=Math.max(0,end-new Date());setLeft({d:Math.floor(x/864e5),h:Math.floor(x/36e5)%24,m:Math.floor(x/6e4)%60,s:Math.floor(x/1e3)%60})};tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[]);return <div className="count"><div className="wrap countInner"><div><small>HITUNG MUNDUR MENUJU</small><strong>PESTA OLAHRAGA PANTAI 2026</strong></div><div className="timer">{Object.entries(left).map(([k,v])=><div key={k}><b>{String(v).padStart(2,'0')}</b><span>{k}</span></div>)}</div></div></div>}
function NewsCard({n}){return <article className="newsCard"><div className="newsImg"></div><div className="newsBody"><small>{n.cat} • {n.date}</small><h3>{n.title}</h3><span><Eye size={14}/> {n.views} dilihat</span><a>Baca selengkapnya <ArrowRight size={15}/></a></div></article>}
function Page({route,go}){const data={profil:['Profil','Membangun olahraga prestasi yang unggul, berdaya saing, dan berkarakter.'],organisasi:['Organisasi','Struktur pengurus dan unit organisasi olahraga.'],berita:['Berita','Ikuti perkembangan terbaru, prestasi atlet, dan kegiatan pembinaan.'],pengumuman:['Pengumuman','Informasi resmi, tender, dan pemberitahuan terbaru.'],prestasi:['Prestasi','Kumpulan capaian dan cerita juara.'],event:['Event & Kalender','Jadwal kegiatan dan kompetisi olahraga.'],cabor:['Cabang Olahraga','Daftar cabang olahraga yang dibina.'],atlet:['Data Atlet','Direktori atlet dan pencapaian.'],vms:['VMS','Rencana umum pengadaan, lelang, rekanan, dan pendaftaran.'],login:['Login','Masuk ke pusat manajemen strategi olahraga.']}[route]||['Halaman','Konten']; return <main><div className="pageHero"><div className="wrap"><small>INFORMASI</small><h1>{data[0]}</h1><p>{data[1]}</p></div></div><section className="section wrap">{route==='berita'?<ListNews/>:route==='pengumuman'?<AnnouncementPage/>:route==='organisasi'?<Org/>:route==='cabor'?<Sports/>:route==='event'?<Events/>:route==='prestasi'?<Achievements/>:route==='atlet'?<Athletes/>:route==='login'?<Login/>:route==='vms'?<Vms/>:<Generic route={route}/>}</section></main>}
function ListNews(){const [q,setQ]=useState('');const list=useMemo(()=>news.filter(n=>n.title.toLowerCase().includes(q.toLowerCase())),[q]);return <><div className="searchbar"><Search/><input placeholder="Cari berita..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="newsGrid">{list.map((n,i)=><NewsCard n={n} key={i}/>)}</div></>}
function AnnouncementPage(){return <div className="announceGrid">{[...announcements,...announcements].map((x,i)=><article className="announce" key={i}><Megaphone/><small>Pengumuman • 2026</small><h3>{x}</h3><p>Informasi resmi dan dokumen terkait kegiatan olahraga.</p><a>Baca <ArrowRight size={15}/></a></article>)}</div>}
function Org(){return <><div className="intro"><p>Susunan pengurus contoh untuk website baru. Data dapat dikelola melalui CMS/backend.</p></div><div className="leaderGrid">{leaders.map((x,i)=><article className="leader" key={x}><div className="avatar">{i+1}</div><small>{x}</small><h3>{['Ardi Pratama','Bima Nugraha','Citra Wulandari','Dimas Saputra','Eka Ramadhan','Fajar Hidayat','Gita Maharani','Hana Putri'][i]}</h3></article>)}</div></>}
function Sports(){return <div className="sportsGrid">{sports.map((x,i)=><article className="sport" key={x}><div className="sportNum">{String(i+1).padStart(2,'0')}</div><h3>{x}</h3><p>Program pembinaan dan prestasi</p><ArrowRight/></article>)}</div>}
function Events(){return <div className="eventList">{['Seleksi Atlet Nasional — Atletik','Kejuaraan Provinsi — Renang','Festival Olahraga Pelajar','Turnamen Antar Klub — Basket','Pemusatan Latihan Nasional'].map((x,i)=><div className="eventRow" key={x}><CalendarDays/><div><small>{5+i} OKT 2026</small><h3>{x}</h3><p>Jakarta • 08.00 WIB</p></div><button>Detail <ArrowRight size={15}/></button></div>)}</div>}
function Achievements(){return <div className="achievementGrid">{['Emas PON','Juara Nasional','Rekor Nasional','Atlet Terbaik'].map((x,i)=><article className="achievement"><Trophy/><small>PRESTASI 2026</small><strong>{12+i*7}</strong><h3>{x}</h3><p>Catatan prestasi olahraga untuk negeri.</p></article>)}</div>}
function Athletes(){return <div className="athleteGrid">{['Andi Saputra','Nadia Pratama','Raka Hidayat','Salsa Putri','Dito Ramadhan','Maya Lestari'].map((x,i)=><article className="athlete"><div className="avatar big">{i+1}</div><small>{sports[i%sports.length]}</small><h3>{x}</h3><span>Atlet Prestasi</span></article>)}</div>}
function Vms(){return <div className="vmsGrid">{['Rencana Umum Pengadaan','Lelang / Tender','Daftar Rekanan','Pendaftaran Rekanan'].map((x,i)=><article className="vmsCard"><strong>0{i+1}</strong><h3>{x}</h3><p>Kelola informasi secara transparan dan terstruktur.</p><button>Masuk <ArrowRight size={15}/></button></article>)}</div>}
function Login(){return <div className="loginBox"><div className="loginMark">SN</div><h2>Pusat Manajemen Olahraga</h2><p>Masuk untuk mengelola data dan konten.</p><label>Username<input/></label><label>Password<input type="password"/></label><button>Login</button></div>}
function Generic({route}){return <div className="generic"><h2>{route==='profil'?'Visi, Misi & Fungsi':''}</h2><div className="genericGrid"><div><Users/><h3>Pembinaan Prestasi</h3><p>Program pembinaan atlet dari pembibitan hingga puncak prestasi.</p></div><div><Trophy/><h3>Kompetisi</h3><p>Penyelenggaraan dan dukungan kompetisi secara berkelanjutan.</p></div><div><Newspaper/><h3>Informasi Terbuka</h3><p>Publikasi berita, agenda, pengumuman, dan capaian olahraga.</p></div></div></div>}
function Footer({go}){return <footer><div className="wrap footerGrid"><div><a className="brand footerBrand" href="#home"><span>SPORT</span><strong>NUSANTARA</strong></a><p>Pusat prestasi olahraga untuk pembinaan atlet, kompetisi, dan kolaborasi.</p></div><div><h4>NAVIGASI</h4><a onClick={()=>go('profil')}>Profil</a><a onClick={()=>go('berita')}>Berita</a><a onClick={()=>go('prestasi')}>Prestasi</a><a onClick={()=>go('event')}>Event</a></div><div><h4>LAYANAN</h4><a onClick={()=>go('atlet')}>Data Atlet</a><a onClick={()=>go('cabor')}>Cabang Olahraga</a><a onClick={()=>go('vms')}>VMS</a></div><div><h4>KONTAK</h4><p><MapPin size={15}/> Jakarta, Indonesia</p><p><Phone size={15}/> +62 21 0000 0000</p><p><Mail size={15}/> info@sportnusantara.id</p></div></div><div className="copyright">© 2026 Sport Nusantara. Template baru terinspirasi dari pola navigasi portal olahraga publik.</div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
